# SEO content

title : SproutIQ Garden Planner
tagline: Add any plant to your garden layout with SproutIQ!  
description: Our drag-and-drop garden planner allows you to add unique plant varieties from a photo or url. Why limit yourself to a database, when you can tap into the entire internet?
url: https://sproutiq.app/
logo: assets/appicon.png


# Page content

#page title
page_title                                : SproutIQ                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 6741376768                               # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                          # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                          # Enter Google Play Store URL.
presskit_download_link                    :                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : SproutIQ Garden Planner                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Scan, Plan, Plant, Grow with SproutIQ Garden Planner! The only garden layout planner that allows you to add custom plants with just a photo of your seed packet or growing guide.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.

# Information About Yourself
your_name                                 : Neural Appworks LLC                                
your_link                                 :                      
your_city                                 :                                 
email_address                             : contact@neuralappworks.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : 
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Plan
    description                           : Visually plan your garden with the drag-and-drop interface of the garden layout tool
    fontawesome_icon_name                 : fa-leaf

  - title                                 : Explore
    description                           : Choose from 200+ varieties or easily add custom plants to your garden using a quick photo, hand-written notes, or any growing guide url
    fontawesome_icon_name                 : fa-camera

  - title                                 : Learn 
    description                           : Chat with your garden! The chatbot gives tailored advice based on your custom plant list, your local frost dates and much more!
    fontawesome_icon_name                 : fa-graduation-cap

  - title                                 : Grow
    description                           : Start the right number of seeds, every time! Each garden layout has a plant inventory so you always know how many youâ€™ll need for your space
    fontawesome_icon_name                 : fa-star

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/header.jpg                 # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.7

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown

plugins:
  - jekyll-seo-tag